### ISSUE TITLE
Query: USART RX FIFO

### ISSUE THREAD

**Issue by rxa1031** [STMicroelectronics/STM32CubeH7#130]
Hello,

I am using STM32CubeMX version 6.2.0 and STM32CubeH7 version 1.9.0.

I am concerned about the Asynchronous USART FIFO related settings, which I shall describe later in this discussion.

**Pre-condition:**
1. Independent cyclic buffers exist for TX and RX data.
2. A Transmit task would write to the TX Buffer array (C variable), which will then be used in USART1 IRQ Handler to send out data. The Write task will only trigger TXE Interrupt (assuming FIFO not used) and let the IRQ Handler perform rest of the Functionality. (I am not sure whether to use TXFT or TXFE ISR bits in case of FIFO use enable)
3. A Task would check number of bytes available in RX Buffer array (C variable), and will use them if the number of available bytes are positive.
4. The USART1 IRQ handler code must always be ready to receive any byte that is sent to it. Code will _NOT call_ functions like the HAL_USART_Receive_IT() function to start receiving bytes.

**Inputs from my colleague:**
1. Enable FIFO for both transmit and receive, with a 1/8 Depth threshold setting. _In fact, if the FIFO is not enabled, it can be difficult for the CPU to keep up with fast incoming data._
2. Code does not have to depend on RX FIFO interrupts like the _RXFT_ and _RXFF_ but can rather use the _RXFNE_ interrupt for receiving bytes.

**Concerns:**
1. I request your suggestion on my colleague's input.
2. I am assume my colleague's inputs are correct. However, if this is not the case, then while using the Asynchronous UART HAL or LL Driver, I am not sure how one could _ENABLE FIFO only for TX_, and _leave FIFO DISABLE for RX_ (to receive even a single byte)
3. If above is not possible then how to receive one byte using RX FIFO with USART_CR3_RXFTCFG = 0b000 and USART_CR3_RXFTIE = 1.
4. Is there a possibility to use IDLE, CTS and RTS to know when Reception started and when it ended? If so may you please help me understand more about this.

**My understanding of RX FIFO:**
1. There are maximum of 16 RX FIFO available.
2. With USART_CR3_RXFTIE = 1, the smallest number of received bytes for which the interrupt will trigger is _2 bytes_. This can be set by setting USART_CR3_RXFTCFG = 0b000. Thus if only one byte is received, then this interrupt will not trigger.

If I manually make changes to code and later regenerate code using the STM32CubeMX tool any changes made to (non user related) STM32CubeMX generated code parts will get overwritten.

Please help.

Thanks,
Rajeev

**Comment by ASELSTM** [comment]
Hi @rxa1031, 

The following are answers to the different questions raised within **"Inputs from my colleague"** section :

1. The FIFO feature is indeed useful for fast data transfer and it allows the CPU to keep up with fast incoming data.

2. The user code may depend on both  RXFT and RXFF interrupts as well as RXFNE. However, only RXFNE is managed within the `HAL_UART_IRQHandler()`. For the rest it's up to the user to handle them and define his own interruption routines to execute when RXFT or RXFF interrupts are set.

The following are answers to the different questions raised within **"Concerns"** section : 

1. Answered in the section above.

2. Enabling the FIFO feature will automatically enable the transmit FIFO (TXFIFO) and the receive FIFO (RXFIFO). It is not possible to activate only one of them. However, you have the ability to enable or disable the interruptions related to the transmit FIFO or receive FIFO thru **USART_CR1_RXFFIE** and **USART_CR1_TXFEIE** bits. 
It is also possible to handle separately the transmit and receive FIFO threshold configurations as well as enabling or disabling the RXFIFO and TXFIF threshold interrupt separately using **USART_CR3_RXFTIE** and **USART_CR3_TXFTIE**.

3. It is actually possible to receive one byte using the RXFIFO by setting the data to be received to 1. However, you won't be able to fully exploit the FIFO feature's interruptions especially interruptions related to the RXFIFO threshold.  Since the depth of the RXFIFO is 16 bytes and the `USART_CR3_RXFTCFG = 0b000` then the threshold is equal to 2 bytes thus Receive FIFO will never reaches the programmed threshold and RXFT flag will never be set. Not to mention that the RXFF flag will also never be set since the number of received data will never reach the FIFO depth.

4.  Below some details about the `IDLE` `CTS` and `RTS` and their main use :

-  **IDLE** is used to detect _inactivity periods_. The IDLE Line event is triggered when RX line has been in idle state for one frame time, after last received byte. The frame time is mainly based on the baud rate. The higher the baud rate, the shorter the frame time.

**CTS and RTS**  are used for hardware flow control. The objective of the CTS and RTS is to remove the need for handshaking.

- The **RTS** (Request to Send) is tied low as long as the USART receiver is ready to receive a new data. When the receive register is full, RTS is de-asserted, indicating that the transmission is expected to stop at the end of the current frame.

- The **CTS**  (Clear to Send) indicates when the receiver becomes ready or not for communication. If CTS is tied low, then the next data is transmitted, else the transmission does not occur. When CTS is de-asserted during a transmission, the current transmission is completed before the transmitter stops.

The following are answers to the different questions raised within **"My understanding of RX FIFO"** section : 

1. Indeed, the depth of the FIFO is 16 bytes.

2. As explained upper in the **Concerns** section. The FIFO depth is 16 bytes and the minimum threshold is 2 bytes. So,  if the data to be received is equal to one byte the RXFT interrupt will not trigger.


I hope I have answered all your questions and that this would help you.

With regards,
