### ISSUE TITLE
Nucleo-H753ZI BUG in default configuration

### ISSUE THREAD

**Issue by mikebargauan** [STMicroelectronics/STM32CubeH7#140]
STM32Cube ver 1.6.1 with STM32Cube_FW_H7_V1.9.0 - select Nucleo-H753ZI with default configuration and generate new project - add some activity like 	  
HAL_GPIO_WritePin(GPIOB, LD3_Pin, GPIO_PIN_SET); 
HAL_Delay(1000);
HAL_GPIO_WritePin(GPIOB, LD3_Pin, GPIO_PIN_RESET);
HAL_Delay(1000);
in while loop ( after USER CODE BEGIN 3).
NOT WORKING
From debug, system hangs up in MX_USART3_UART_Init() ==> HAL_UART_Init() ==> UART_CheckIdleState() ==> UART_WaitOnFlagUntilTimeout() ...
Disable USART3 and it works.

Mike Bargauan

**Comment by ASELSTM** [comment]
Hi @mikebargauan,

This issue is rather related to the **STM32CubeMx** tool and it may be due to the fact that you are using an old version of STM32CubeMx tool. Please make sur you using the latest version [V6.2.0](https://www.st.com/en/development-tools/stm32cubemx.html#get-software).

Actually, aspects related to tools are not handled at GitHub level. They are rather treated at **ST Community** level, precisely within the **CubeMX** dedicated [section](https://community.st.com/s/topic/0TO0X000000BTr8WAG/stm32cubemx) . There, you may find posts that already raised the issue you are pointing out here. Otherwise, you can create a new post to submit your issue.

As this issue is not directly related to software component published within this repository (CMSIS, HAL, BSP, etc.) but rather to ecosystem (CubeMX tool, CubeIDE tool), please allow me to close it.

Thank you for your comprehension and thank you again for your contribution. We are looking forward to reading from you again.

With regards,
