### ISSUE TITLE
Unable to generate .gpdsc file from proj for H745

### ISSUE THREAD

**Issue by fazerlicourice7** [STMicroelectronics/STM32CubeH7#168]
In STM32CubeMX, the `Other Toolchains (gpdsc)` options is unavailable for the H745ZI (I'm using the nucleo h745zi-q). On stm32Cubemx 6.2.1.

I would like to use the .gpdsc file to use a different compiler / toolchain than the given options, but I'm unable to do so because it is not an option.

**Comment by RKOUSTM** [comment]
Hi @fazerlicourice7,

Thank you for this report.  However, the point you reported is related to the CubeMX generation problem and not directly related to the firmware published in this repository. Unfortunately we don't treat aspect related to CubeMX tool in our GitHub repositories.  Indeed, all aspects related to Cube MX tool are not handled at GitHub level. They are rather treated at ST Community level, precisely within the Cube MX dedicated [section] (https://community.st.com/s/topic/0TO0X000000BSqSWAW/stm32-mcus) .

Now, as this issue is not directly related to some software component published within this repository (CMSIS, HAL, BSP, etc.) but rather to our ecosystem (namely the Cube MX tool), please allow me to close it.

Thank you for your comprehension. We are looking forward to reading from you again.

With regards,
