### ISSUE TITLE
Can provide CubeMX configuration file？

### ISSUE THREAD

**Issue by arilink** [STMicroelectronics/STM32CubeH7#173]
I bought the H735 Discovery development board for learning. The simple peripherals are okay. But when I studied in depth, I encountered a problem with SD QSPI. I don’t know how to configure it correctly through CubeMX and generate code like a routine. Can you please? Do you provide CubeMX files for learning?

**Comment by ASELSTM** [comment]
Hi @arilink,

Thank you for your contribution.  Unfortunately, we don't treat aspect related to CubeMX tool in our GitHub repositories.  They are rather treated at the [STM32CubeMX](https://community.st.com/s/topic/0TO0X000000BTr8WAG/stm32cubemx) dedicated page of the **ST Community**.  There, you may find posts that already raised the issue you are pointing out here. Otherwise, you can create a new post to submit your issue . 

Since this issue is not directly related to the STM32Cube firmware but rather to our ecosystem, please allow me then to close this thread. Thank you for your comprehension. 

With regards,
