### ISSUE TITLE
stm32h7xxx_discovery_conf_template.h replace with the actual stm32h7xxx_discovery_conf.h from the BSP example folder

### ISSUE THREAD

**Issue by VictorTagayun** [STMicroelectronics/STM32CubeH7#207]
Why is stm32h7xxx_discovery_conf.h not in the BSP folder in STM32Cube_FW_H7_Vn.nn.n\Drivers\BSP\STM32H7xxxx?
Instead, stm32h7xxx_discovery_conf_template.h is there.
I still need to copy from the BSP example for the correct definitions and other things.

**Comment by RKOUSTM** [comment]
Hi @VictorTagayun,
 
Thank you for your report. According to our development team, the stm32h7xxx_discovery_conf_template.h file is a user file, while the stm32h7xxx_discovery_conf.h file is a customizable file for each application. In order to emphasize each use case, a generic file is proposed as a reference template. 

Please allow me to close this issue now. Thank you once again for your report. We are looking forward to reading from you again.

With regards,
