### ISSUE TITLE
STM32CUBEMX V6.5 cannot configure the ADC clock of some chips

### ISSUE THREAD

**Issue by chenjingyuanku** [STMicroelectronics/STM32CubeH7#211]
When I use STM32CUBEMX V6.5, I cannot configure the ADC clock for chips such as STM32H750VB/743VI.

**Comment by ASELSTM** [comment]
Hi @chenjingyuanku,

Thank you for this report. The point you reported is actually related to the **CubeMX** generation problem and not to the firmware published in this repository. Unfortunately, we don't treat aspect related to CubeMX tool in our GitHub repositories.  They are rather treated at the [STM32CubeMX](https://community.st.com/s/topic/0TO0X000000BTr8WAG/stm32cubemx) dedicated page of the **ST Community** . 

Since this issue is not directly related to the STM32Cube firmware but rather to our ecosystem, please allow me then to close this thread. Thank you for your comprehension. 

With regards,
