### ISSUE TITLE
SPI with DMA in stm32H750VB 

### ISSUE THREAD

**Issue by pooriyaadh** [STMicroelectronics/STM32CubeH7#229]
Hi  , These days I have a challenge to Transfer data between two stm32h750 With SPI  .
If I use hal_spi_Transmit_Recieve for both of them it's working but if I add DMA to them They don't Transmit and receive anything 
After I search about it , The best solution is to use SPI_FullDuplex_ComDMA Example for my project.
My question is The example is for stm32h743zi microcontroller  , 
Can I use These Example for stm32h750vb?
I have some Doubt  , if The memory management and things like that is difference from stm32h743zi.

**Comment by RJMSTM** [comment]
Hello @pooriyaadh,

First, allow me to thank you for your report. However, the point you reported is not directly related to the firmware published in this repository and we don't treat aspect related to user application in our GitHub repositories. They are rather treated at [ST Community](https://community.st.com/s/topic/0TO0X000000BSqSWAW/stm32-mcus) level.

Now, as this issue is not directly related to some software component published within this repository (CMSIS, HAL, BSP, etc.) but rather to a user application, please allow me to close it.

Thank you for your comprehension. We are looking forward to reading from you again.

With regards,
