### ISSUE TITLE
STM32CubeMX code generator is calling ethernetif_input instead of ethernet_link_thread.

### ISSUE THREAD

**Issue by david-oz00** [STMicroelectronics/STM32CubeH7#23]
**Describe the set-up**
* Hardware:  Proprietary hardware containing STM32H743 and external FLASH and external SDRAM.
* IDE:  VisualGDB with GCC 9.2.1
* FreeRTOS: V10.1.2
* CMSIS: V2.0
* Package:  STM32Cube FW_H7 V1.6.0

**Describe the bug**
When LWIP_NETIF_LINK_CALLBACK is enable in the STM32CubeMX LWIP middleware, it generates the following code from the FW_H7 V1.6.0 package:

```
/* Set the link callback function, this function is called on change of link status*/
  netif_set_link_callback(&gnetif, ethernet_link_status_updated);
 
  /* Create the Ethernet link handler thread */
  memset(&attributes, 0x0, sizeof(osThreadAttr_t));
  attributes.name = "EthLink";
  attributes.stack_size = INTERFACE_THREAD_STACK_SIZE;
  attributes.priority = osPriorityRealtime;
  osThreadNew(ethernetif_input, &gnetif, &attributes);

```
In the last line, it is starting a thread with an entry function of ethernetif_input.  However, that function has nothing to do with the ethernet link status.  Previous versions of this package used an entry function for the thread called ethernet_link_thread.

**How To Reproduce**
1. Indicate the global behavior of your application project
Proprietary application with Ethernet port and LWIP as the TCP/IP stack.

2. The modules that you suspect to be the cause of the problem (Driver, BSP, MW ...)
The **_MX_LWIP_Init()_** function in the file **_lwip.c_**.

3. The use case that generates the problem
See (4)

4. How we can reproduce the problem
Create an STM32CubeMX project that uses the FW_H7 V1.6.0 package and includes LWIP middleware with the LWIP_NETIF_LINK_CALLBACK option enabled. The code that initiates the thread that monitors the Ethernet link uses the wrong start function.

**Additional context**
This code in MX_LWIP_Init():
`osThreadNew(ethernetif_input, &gnetif, &attributes);`
should be changed to:
`osThreadNew(ethernet_link_thread, &gnetif, &attributes);`

**Screenshots**

**Comment by ALABSTM** [comment]
Hi David,

First, allow me to thank you for all the points you are raising through these issues. However, aspects related to Cube MX tool are not handled at GitHub level. They are rather treated at **ST Community** level, precisely within the [Cube MX](https://community.st.com/s/topic/0TO0X000000BTr8WAG/stm32cubemx) dedicated section.

There, you may find posts that already raised the issue you are pointing out here. Otherwise, you can create a new post to submit your issue. Please, allow me to close this issue. Thank you for your comprehension.

With regards,
