### ISSUE TITLE
Confusing configuration of ADC trigger at CubeMX (STM32H750)

### ISSUE THREAD

**Issue by gripennn** [STMicroelectronics/STM32CubeH7#45]
At register level selecting ADC trigger event is done thru EXTSEL with many internal sources (timers) and one external (EXTI Line 11). Consistent approach is in LL API, where selecting trigger source by "LL_ADC_REG_SetTriggerSource" function or thru LL_ADC_REG_InitTypeDef TriggerSource. But in CubeMX is that configuration splited in two places with confusing labels.

![menu1](https://user-images.githubusercontent.com/20212110/85111553-c99fbb00-b214-11ea-98b5-ff93f3f12e75.jpg)
![menu2](https://user-images.githubusercontent.com/20212110/85111557-cad0e800-b214-11ea-9a35-c37b02b63d2c.jpg)

If i want to select internal triggers i have to select literaly "Conversion trigger Disable" (realy confusing because by this option in reality i am enabling internal trigger source selections - or in other words i am disabling only one specific trigger source (EXTI)). In addition internal trigger sources are called "External Trigger Conversion Sources". I suppose that both these options should be merged into one configuration field to correspond with logic of reference manual... 

version of CubeMX 5.6.1

**Comment by RKOUSTM** [comment]
Hi @gripennn,

Thank you for your contribution. According to our analysis, this issue is rather related to CubeMX, may I ask you to submit it to the ST Community in the dedicated [section](https://community.st.com/s/topic/0TO0X000000BTr8WAG/stm32cubemx)? There, you will hopefully find people from our CubeMX development teams who will take in charge your request.

Thank you again for your contribution.

With regards,
