### ISSUE TITLE
STM32CubeMX adds incorrect value to XTAL

### ISSUE THREAD

**Issue by rxa1031** [STMicroelectronics/STM32CubeH7#66]
Hello,

I have been observing this issue with previous as well as latest STM32CubeMX versions, wherein the generated MDK-ARM (minimum version 5.27) project file (UVPROJX) has incorrect value set to Options for Target -> Target -> Xtal (MHz).
In the IOC file I have informed that used XTAL value is 25 MHz.

In Clock configuration, I have set SYSCLK to 480 MHz and D1CPRE Prescaler to Divide by 1. thus FCLK is 480 MHz.

STM32CubeMX copying SYSCLK value to Xtal (MHz) is a BUG.

Please fix the bug.

Regards,
@rxa1031

**Comment by RKOUSTM** [comment]
Hi @rxa1031,

Thank you for your contribution. Our development teams confirmed that this issue is rather related to CubeMX. Unfortunately we don't treat aspect related to CubeMx tool in our GitHub repositories.

Please allow me to redirect you to our ST Community. You can report this issue in the [CubeMX related section](https://community.st.com/s/topic/0TO0X000000BTr8WAG/stm32cubemx). There, you will hopefully find people from our CubeMX development teams who will take in charge your request.

Thank you for your contribution.

With regards,
