### ISSUE TITLE
UART LL Driver issues

### ISSUE THREAD

**Issue by rxa1031** [STMicroelectronics/STM32CubeH7#69]
Hello,

I am observing following function calls missing from `MX_UART8_Init()` function:

Even when ClockPrescaler, FIFO Mode Disabled, etc. are defined.

```
UART_InitStruct.PrescalerValue = LL_USART_PRESCALER_DIV10;
LL_USART_SetTXFIFOThreshold(UART8, LL_USART_FIFOTHRESHOLD_1_8);
LL_USART_SetRXFIFOThreshold(UART8, LL_USART_FIFOTHRESHOLD_1_8);
LL_USART_DisableFIFO(UART8);
```

![image](https://user-images.githubusercontent.com/18160755/95128949-d3274180-0777-11eb-8075-126c07d34489.png)

Regards,
Rajeev

**Comment by ASELSTM** [comment]
Hi  @rxa1031,

First, allow me to thank you for your contribution.

However, this issue is rather related to **CubeMX** than to the firmware published within this repository.
In fact, aspects related to CubeMX tool are not handled at GitHub level. They are rather treated at **ST Community** level, precisely within the CubeMX dedicated [section](https://community.st.com/s/topic/0TO0X000000BTr8WAG/stm32cubemx). There, you may find posts that already raised the issue you are pointing out here. Otherwise, you can create a new post to submit your issue.

Since this issue is out of our scope, please allow me to close this thread. Thank you for your comprehension.

With regards,
