### ISSUE TITLE
Duplicate include call for stm32h7xx_hal.h in file main.h

### ISSUE THREAD

**Issue by rxa1031** [STMicroelectronics/STM32CubeH7#74]
Hello,

When using FreeRTOS with CMSIS Version 2, I am observing two include calls made to stm32h7xx_hal.h on line numbers 31 and 32 in file main.h

Please remove one of the two include.

Thanks,
Rajeev

**Comment by ASELSTM** [comment]
Hi @rxa1031,

Thank you for this other report.

I suppose you have used **STM32CubeMX** tool to generate the code. Unfortunately, aspects related to CubeMX tool are not handled at GitHub level. They are rather treated at **ST Community** level, precisely within the CubeMX dedicated [section](https://community.st.com/s/topic/0TO0X000000BTr8WAG/stm32cubemx). There, you may find posts that already raised the issue you are pointing out here. Otherwise, you can create a new post to submit your issue.

Since this issue is out of our scope, please allow me to close this thread. Thank you for your comprehension and thank you again for your contribution.

With regards,
