### ISSUE TITLE
CubeMX GPIO not initialized in STM32H747-DISCO?

### ISSUE THREAD

**Issue by VictorTagayun** [STMicroelectronics/STM32CubeH7#88]
[https://community.st.com/s/question/0D53W00000NUOGLSA5/cubemx-gpio-not-initialized-in-stm32h747disco](https://community.st.com/s/question/0D53W00000NUOGLSA5/cubemx-gpio-not-initialized-in-stm32h747disco )

**Comment by ASELSTM** [comment]
Hi @VictorTagayun,

This issue is  related to **CubeMX** than to the firmware published within this repository. In fact, aspects related to CubeMX tool are not handled at GitHub level. They are rather treated at **ST Community** level, precisely within the CubeMX dedicated [section](https://community.st.com/s/topic/0TO0X000000BTr8WAG/stm32cubemx). There, you may find posts that already raised the issue you are pointing out here. Otherwise, you can create a new post to submit your issue.

Since this issue is out of our scope, please allow me to close this thread. Thank you for your comprehension and thank you again for your contribution.

With regards,
