### ISSUE TITLE
function osEventFlagsWait, bug associated with osFlagsWaitAll

### ISSUE THREAD

**Issue by rxa1031** [STMicroelectronics/STM32CubeH7#98]
Hello @RKOUSTM ,

The below line of code needs a fix:
https://github.com/STMicroelectronics/STM32CubeH7/blob/beced99ac090fece04d1e0eb6648b8075e156c6c/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/cmsis_os2.c#L1179

as informed in one of the other threads:
https://github.com/STMicroelectronics/STM32CubeL4/issues/7

Regards,
Rajeev

**Comment by RKOUSTM** [comment]
Hi @rxa1031,

Thank you for your contribution.  This issue has also been previously reported by other users ([link](https://github.com/STMicroelectronics/STM32CubeL4/issues/7)).

This bug is already fixed in the latest [CMSIS-FreeRTOS](https://github.com/ARM-software/CMSIS-FreeRTOS/blob/develop/CMSIS/RTOS2/FreeRTOS/Source/cmsis_os2.c) release. We are planning to update the STM32CubeH7 with the latest CMSIS-FreeRTOS version to integrate this fix. We still cannot share a date for the moment for the integration. We will keep you informed.

Please allow me to close this issue now. Thank you again for your contribution.

With regards,
